// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrrpljbprqiobcxbyuok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycnBsamJwcnFpb2JjeGJ5dW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTM4MjAsImV4cCI6MjA2MTY2OTgyMH0.uDJsM_mzz9lVvPp92Z7JGWKUVOn7a4qkg8HDHAaQXjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);